In [6]:
import numpy as np

In [7]:
import pandas as pd

In [8]:
import matplotlib.pyplot as plt

In [9]:
%matplotlib inline

In [10]:
data = pd.read_csv(r"D:\MachineLearning\A-Z Machine Learning\P14-Part8-Deep-Learning\Section 35 - Artificial Neural Networks (ANN)\Python\Churn_Modelling.csv")

In [11]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [12]:
x = data.iloc[:, 3:-1]
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [13]:
y = data.iloc[:, -1].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [14]:
x_geo = pd.get_dummies(x['Geography'], drop_first=True)
x_geo

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [15]:
x_gen = pd.get_dummies(x['Gender'], drop_first=True)
x_gen

Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [16]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [17]:
x = pd.concat([x_geo, x], sort=True, axis=1)

In [18]:
x

Germany  Spain  CreditScore Geography  Gender  Age  Tenure    Balance  \
0           0      0          619    France  Female   42       2       0.00   
1           0      1          608     Spain  Female   41       1   83807.86   
2           0      0          502    France  Female   42       8  159660.80   
3           0      0          699    France  Female   39       1       0.00   
4           0      1          850     Spain  Female   43       2  125510.82   
...       ...    ...          ...       ...     ...  ...     ...        ...   
9995        0      0          771    France    Male   39       5       0.00   
9996        0      0          516    France    Male   35      10   57369.61   
9997        0      0          709    France  Female   36       7       0.00   
9998        1      0          772   Germany    Male   42       3   75075.31   
9999        0      0          792    France  Female   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0                 1          1               1        101348.88  
1                 1          0               1        112542.58  
2                 3          1               0        113931.57  
3                 2          0               0         93826.63  
4                 1          1               1         79084.10  
...             ...        ...             ...              ...  
9995              2          1               0         96270.64  
9996              1          1               1        101699.77  
9997              1          0               1         42085.58  
9998              2          1               0         92888.52  
9999              1          1               0         38190.78  

[10000 rows x 12 columns]

In [19]:
x = pd.concat([x_gen, x], sort=True, axis=1)
x

Male  Germany  Spain  CreditScore Geography  Gender  Age  Tenure  \
0        0        0      0          619    France  Female   42       2   
1        0        0      1          608     Spain  Female   41       1   
2        0        0      0          502    France  Female   42       8   
3        0        0      0          699    France  Female   39       1   
4        0        0      1          850     Spain  Female   43       2   
...    ...      ...    ...          ...       ...     ...  ...     ...   
9995     1        0      0          771    France    Male   39       5   
9996     1        0      0          516    France    Male   35      10   
9997     0        0      0          709    France  Female   36       7   
9998     1        1      0          772   Germany    Male   42       3   
9999     0        0      0          792    France  Female   28       4   

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0          0.00              1          1               1        101348.88  
1      83807.86              1          0               1        112542.58  
2     159660.80              3          1               0        113931.57  
3          0.00              2          0               0         93826.63  
4     125510.82              1          1               1         79084.10  
...         ...            ...        ...             ...              ...  
9995       0.00              2          1               0         96270.64  
9996   57369.61              1          1               1        101699.77  
9997       0.00              1          0               1         42085.58  
9998   75075.31              2          1               0         92888.52  
9999  130142.79              1          1               0         38190.78  

[10000 rows x 13 columns]

In [20]:
x.drop(['Geography','Gender'], inplace=True, axis=1)

In [21]:
x

Male  Germany  Spain  CreditScore  Age  Tenure    Balance  \
0        0        0      0          619   42       2       0.00   
1        0        0      1          608   41       1   83807.86   
2        0        0      0          502   42       8  159660.80   
3        0        0      0          699   39       1       0.00   
4        0        0      1          850   43       2  125510.82   
...    ...      ...    ...          ...  ...     ...        ...   
9995     1        0      0          771   39       5       0.00   
9996     1        0      0          516   35      10   57369.61   
9997     0        0      0          709   36       7       0.00   
9998     1        1      0          772   42       3   75075.31   
9999     0        0      0          792   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0                 1          1               1        101348.88  
1                 1          0               1        112542.58  
2                 3          1               0        113931.57  
3                 2          0               0         93826.63  
4                 1          1               1         79084.10  
...             ...        ...             ...              ...  
9995              2          1               0         96270.64  
9996              1          1               1        101699.77  
9997              1          0               1         42085.58  
9998              2          1               0         92888.52  
9999              1          1               0         38190.78  

[10000 rows x 11 columns]

In [22]:
x = x.values

In [23]:
x

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc = StandardScaler()

In [26]:
sc.fit_transform(x)

array([[-1.09598752, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.09598752, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.09598752, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-1.09598752, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 0.91241915,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-1.09598752, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [29]:
import tensorflow as tf

In [2]:
import keras

Using TensorFlow backend.


In [3]:
from keras.models import Sequential

In [4]:
from keras.layers import Dense

In [5]:
classifier = Sequential()

In [30]:
classifier.add(Dense(output_dim= 6, init= 'uniform', activation= 'relu', input_dim= 11))

c:\users\my\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [31]:
classifier.add(Dense(output_dim= 6, init= 'uniform', activation= 'relu'))

c:\users\my\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [32]:
classifier.add(Dense(output_dim= 1, init= 'uniform', activation= 'sigmoid'))

c:\users\my\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [33]:
classifier.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [34]:
classifier.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 5s 673us/step - loss: 0.5586 - accuracy: 0.7871
Epoch 2/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.5254 - accuracy: 0.7956
Epoch 3/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.5206 - accuracy: 0.7954
Epoch 4/100
8000/8000 [==============================] - 2s 274us/step - loss: 0.5121 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 234us/step - loss: 0.5071 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.5037 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 2s 245us/step - loss: 0.5044 - accuracy: 0.7959
Epoch 8/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.5016 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.5009 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 2s 221us/step - loss: 0.4982 - accuracy: 0.7960
Epoch 79/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.4982 - accuracy: 0.7960
Epoch 80/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.4982 - accuracy: 0.79600s - loss: 0.4950 - ac
Epoch 81/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.4982 - accuracy: 0.79600s - loss:
Epoch 82/100
8000/8000 [==============================] - 2s 226us/step - loss: 0.4982 - accuracy: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4982 - accuracy: 0.7960
Epoch 84/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.4981 - accuracy: 0.7960
Epoch 85/100
8000/8000 [==============================] - 2s 251us/step - loss: 0.4982 - accuracy: 0.7960
Epoch 86/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.4981 - accuracy: 0.7960
Epoch 87/100
8000/8000 [===

In [35]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [37]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

In [38]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [43]:
from sklearn.metrics import confusion_matrix, classification_report

In [40]:
confusion_matrix(y_test, y_pred)

array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [44]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1595
           1       0.00      0.00      0.00       405

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000



c:\users\my\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
